### PR TITLE
Some performance and compatibility improvements.

### PR DESCRIPTION
**Pull request by Vigen10**
## 1. TemplateCache integration
Added grunt plugin called "grunt-angular-templates". During compilation it's writes the content of view html files into .tmp/templates.js (inline html). Then it copies that file into project. 
After compilation the .tmp folder is removed and also the views directory.

## 2. added delay to push notifications subscribe
The push notification subscription request ('/subscriptions') was making the server unavailable for a couple of seconds. Because of this further requests failed and was affecting the load time, also after loading wallet was not initialized. Delayed subscription request will not interfere the initial requests and will be made after them.

## 3. added Android support library v4, removed support library v13
Support library v4 was throwing an error during compilation, because after android 6 the permissions restrictions and request types are changed. This commit removes the v4 library and replaces it with v23, which will make compatibility with old devices.

### CODE REVIEW

**Comment by troggy** [comment]
Thanks for your help! I will review the changes and merge. Please create separate PR for each improvement next time.

**Comment by alexgulko** [comment]
Noted. Thank you too.

**Comment by troggy** [comment]
Sorry, it took a while to get my attention to this. I've started reviewing this one.

First issue: template inlining messes up "Backup" screen. There is no space between mnemonic words anymore. I verified this problem goes away if I remove inlined templates.

image

**Comment by troggy** [comment]
cc @alexgulko

**Comment by troggy** [comment]
that's it because of `collapseWhitespace`. There is whitespace used to separate the words, hence the issues. Can be fixed by either disabling `collapseWhitespace` or by making space between the words using CSS (proper way)

**Comment by troggy** [comment]
Merged with a "collapseWhitespace" set to false for template plugin. Let me know if it is not working for you

**Comment by Vigen10** [comment]
Thank you @troggy !

**Pull request merged**
